### ISSUE TITLE
Suggestion for your list :)

### ISSUE THREAD

**Issue by shuckster** [leonardomso/awesome-fsm#4]
A bit of self-promotion I'm afraid, but I wrote an FSM you can find over [here](https://github.com/shuckster/statebot). It's [well documented](https://shuckster.github.io/statebot/), so I hope it's a valuable addition.

Thanks for the [Reddit thread](https://www.reddit.com/r/javascript/comments/himkd7/awesome_list_of_finite_state_machines_and/), too! That's how I found your list. :)

**Comment by leonardomso** [comment]
Nice! Please open a PR let's add your project to the list.

**Comment by shuckster** [comment]
Thanks! Just created one. Hope it's alright!

**Comment by leonardomso** [comment]
Merged!
